# Generated by Django 6.0.1 on 2026-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=150, unique=True)),
                ('category', models.CharField(choices=[('game', "O'yin"), ('character', 'Qahramon'), ('location', 'Joy'), ('item', 'Qurol / Artefakt'), ('faction', 'Tashkilot'), ('lore', 'Afsona')], default='character', max_length=50)),
                ('game_name', models.CharField(default='CyberKurgan: Legend of Islom', max_length=200)),
                ('default_language', models.CharField(default='uz', max_length=10)),
                ('translations', models.JSONField(default=dict, help_text='JSON format multilingual translations')),
                ('views', models.IntegerField(default=0)),
                ('author', models.CharField(default='WikiKurgan Editor', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
